fix: `/media/ ` url mapping should be "added" instead of "appended"
static() returns a list. Using `append` will put this list as an item within the urlpatterns list, instead of being combined with the urlpatterns list.

One of the ways this mistake surfaces itself (aside from media urls not working) is when making migrations:

```
SystemCheckError: System check identified some issues:

ERRORS:
?: (urls.E004) Your URL pattern [<URLPattern '^media/(?P<path>.*)$'>] is invalid. Ensure that urlpatterns is a list of path() and/or re_path() instances.
```